In [23]:
import os
from PIL import Image
import numpy as np


# Set the directory you want to start from
rootDir = '/home/joker/assigment_imgs'
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)

main_list = np.zeros([len(fileList), 200, 200, 3])
for i in range(len(fileList)):
    im = Image.open(dirName+"/"+fileList[i])
    new_image = im.resize((200, 200))
    resized_array = np.array(new_image)
    main_list[i] = resized_array
    
print(main_list, '\n', np.shape(main_list))
print(resized_array.shape)

Found directory: /home/joker/assigment_imgs
	05.jpeg
	17.jpeg
	13.jpeg
	01.jpeg
	11.jpeg
	04.jpeg
	19.jpeg
	bike.jpeg
	03.jpeg
	15.jpeg
	ninja.jpeg
	09.jpeg
	10.jpeg
	06.jpeg
	16.jpeg
	20.jpeg
	18.jpeg
	12.jpeg
	08.jpeg
	02.jpeg
	14.jpeg
	07.jpeg
[[[[234. 234. 234.]
   [234. 234. 234.]
   [234. 234. 234.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[234. 234. 234.]
   [234. 234. 234.]
   [234. 234. 234.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  [[234. 234. 234.]
   [234. 234. 234.]
   [234. 234. 234.]
   ...
   [255. 255. 255.]
   [255. 255. 255.]
   [255. 255. 255.]]

  ...

  [[206. 206. 206.]
   [206. 206. 206.]
   [206. 206. 206.]
   ...
   [248. 248. 248.]
   [248. 248. 248.]
   [248. 248. 248.]]

  [[206. 206. 206.]
   [206. 206. 206.]
   [206. 206. 206.]
   ...
   [248. 248. 248.]
   [248. 248. 248.]
   [248. 248. 248.]]

  [[206. 206. 206.]
   [206. 206. 206.]
   [206. 206. 206.]
   ...
   [248. 248. 248.]
   [248. 248. 

In [22]:
import os
from PIL import Image
import numpy as np


# Set the directory you want to start from
rootDir = '/home/joker/assigment_imgs'
for dirName, subdirList, fileList in os.walk(rootDir):
    print('Found directory: %s' % dirName)
    for fname in fileList:
        print('\t%s' % fname)

main_list = np.zeros([len(fileList), 200, 200, 3])
for i in range(len(fileList)):
    im = Image.open(dirName+"/"+fileList[i])
    print('Dowanloaded images shape =', np.shape(im), fileList[i])
    new_image = im.resize((200, 200))
    resized_array = np.array(new_image)
    
    #resized_array = (200,200,3)
    #print('Resized images size shape =', resized_array.shape)
    
    main_list[i] = resized_array
    #main_list = +(1,200,200,3)
    #main_list = +(2,200,200,3)
    #main_list = +(3,200,200,3)
    #main_list = +(4,200,200,3)
    #main_list = +(5,200,200,3)
    #main_list = +....
    #main_list = +(21,200,200,3)
    
    
print(main_list, '\n', np.shape(main_list))
print(resized_array.shape)

Found directory: /home/joker/assigment_imgs
	05.jpeg
	17.jpeg
	13.jpeg
	01.jpeg
	11.jpeg
	04.jpeg
	19.jpeg
	bike.jpeg
	03.jpeg
	15.jpeg
	ninja.jpeg
	09.jpeg
	10.jpeg
	06.jpeg
	16.jpeg
	20.jpeg
	18.jpeg
	12.jpeg
	08.jpeg
	02.jpeg
	14.jpeg
	07.jpeg
/home/joker/assigment_imgs
Dowanloaded images shape = (183, 276, 3) 05.jpeg
Dowanloaded images shape = (183, 275, 3) 17.jpeg
Dowanloaded images shape = (182, 277, 3) 13.jpeg
Dowanloaded images shape = (176, 287, 3) 01.jpeg
Dowanloaded images shape = (180, 279, 3) 11.jpeg
Dowanloaded images shape = (168, 300, 3) 04.jpeg
Dowanloaded images shape = (168, 300, 3) 19.jpeg
Dowanloaded images shape = (183, 275, 3) bike.jpeg
Dowanloaded images shape = (168, 300, 3) 03.jpeg
Dowanloaded images shape = (183, 275, 3) 15.jpeg
Dowanloaded images shape = (183, 275, 3) ninja.jpeg
Dowanloaded images shape = (164, 307, 3) 09.jpeg
Dowanloaded images shape = (168, 300, 3) 10.jpeg
Dowanloaded images shape = (183, 275, 3) 06.jpeg
Dowanloaded images shape = (194, 25

In [20]:
import os
from PIL import Image
import numpy as np
import matplotlib.pylab as plt


photos = []
rootDir = '/home/joker/assigment_imgs/'
cntr = 0
size = (200,200,3)
resized = []

for i in os.listdir(rootDir):
    print(i,cntr)
    img = Image.open(rootDir + i)
    img.thumbnail((size), Image.ANTIALIAS)
    photos.append(np.array(img, dtype = 'int32'))
    cntr += 1

print(np.shape(photos), '\n', photos)


05.jpeg 0
17.jpeg 1
13.jpeg 2
01.jpeg 3
11.jpeg 4
04.jpeg 5
19.jpeg 6
03.jpeg 7
15.jpeg 8
09.jpeg 9
10.jpeg 10
06.jpeg 11
16.jpeg 12
20.jpeg 13
18.jpeg 14
12.jpeg 15
08.jpeg 16
02.jpeg 17
14.jpeg 18
07.jpeg 19
(20,) 
 [array([[[234, 234, 234],
        [234, 234, 234],
        [234, 234, 234],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[234, 234, 234],
        [234, 234, 234],
        [234, 234, 234],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[234, 234, 234],
        [234, 234, 234],
        [234, 234, 234],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[206, 206, 206],
        [206, 206, 206],
        [206, 206, 206],
        ...,
        [248, 248, 248],
        [248, 248, 248],
        [248, 248, 248]],

       [[206, 206, 206],
        [206, 206, 206],
        [206, 206, 206],
        ...,
        [248, 248, 2